@extends('layout')
@section('content')


	<div class="holder">

		<h1 id="terms-of-service">Terms of Service</h1>
		<p>THESE TERMS OF SERVICE (“AGREEMENT”) ARE A LEGAL AGREEMENT BETWEEN YOU (“YOU” OR “CUSTOMER”) AND PHOTOS IN THE MAIL (“WE” OR “PHOTOS IN THE MAIL”).  THIS AGREEMENT STATES THE TERMS AND CONDITIONS THAT GOVERN YOUR USE OF THE SITE AND THE PRODUCTS SOLD ON IT AND MEMBERSHIPS SOLD TO IT. BY ACCESSING AND USING THE SITE, YOU ARE INDICATING THAT YOU ACCEPT, AND AGREE TO COMPLY WITH, THIS AGREEMENT. IF YOU DO NOT ACCEPT THIS AGREEMENT, YOU ARE NOT PERMITTED TO, AND YOU MUST NOT, ACCESS OR USE THE SITE OR PURCHASE PRODUCTS FROM, OR MEMBERSHIPS TO, THE SITE.
		By signing up for a Membership (as defined below), you represent, acknowledge and agree that you are at least 18 years of age, or if you are under 18 years of age but are at least 13 years old, that you are using the Site with the consent of your parent or legal guardian and that you have received your parent’s or legal guardian’s permission to enter into this Agreement. If you are a parent or legal guardian who is registering for a child, you hereby agree to bind your child to this Agreement and to fully indemnify and hold harmless PHOTOS in the MAIL if your child breaches or disaffirms any term or condition of this Agreement.</p>

		<h2>1 – CHANGES TO TERMS; PERSONAL INFORMATION/PRIVACY</h2>
		<h3>1.1 – Changes to the site</h3>
		<p>PHOTOS in the MAIL may add to, change or remove any part of the Site, including, without limitation, any Content (as defined below) therein, at any time without prior notice to you.</p>
		<h3>1.2 – Personal Information/Privacy</h3>
		<p>Customers agree to provide accurate, current, and complete information as required for the purchase of the Products and Memberships (both as defined below in Section 3.1). PHOTOS in the MAIL reserves the right to block further sales to Customers who provide false, inaccurate or incomplete data. Customer acknowledges that PHOTOS in the MAIL uses a third party payment processing service to processing orders and bill fees to your credit card. PHOTOS in the MAIL’s Privacy Policy, located at the URL: http://www.photosinthemail.com/privacy-policy (the “Privacy Policy”), explains how Customers’ personally identifiable information is collected, used and disclosed. You hereby agree that we may use your personal information in accordance with the terms of the Privacy Policy.</p>
		<h2>2 – PASSWORDS; USE OF SITE</h2>
		<h3>2.1 – Passwords</h3>
		<p>You are responsible for maintaining the confidentiality of your passwords, and you are responsible for all activities that occur using your passwords. You agree not to share your passwords, let anyone else access your passwords or do anything else that might jeopardize the security of your passwords. You agree to notify PHOTOS in the MAIL if there is any unauthorized use of your password on this Site or if you know of any other breach of security in relation to this Site.</p>
		<h2>3 – TERMS OF SALE</h2>
		<h3>3.1 - Sales of Products and Memberships to End Users Only</h3>
		PHOTOS in the MAIL sells prints of pictures (the “Product(s)”) from the Site to end-user customers who purchase monthly memberships to receive the Products (“Membership(s)”) only for their own personal, non-commercial use. You may not purchase Products or Memberships for further distribution or resale or for any other commercial or business purpose. The Membership and all rights and privileges conferred are personal and non-transferable.</p>
		<h3>3.2 - Pricing</h3>
		<p>Pricing for Products and Memberships (including any applicable shipping and handling fees) can be found on PHOTOS in the MAIL’s then-current pricing page located on the Site at: http://www.photosinthemail.com. The price that we will charge you for the Products and Memberships will be the price as posted on the Site on the date you first sign-up for a Membership to the Site. PHOTOS in the MAIL reserves the right to change prices for Products and Memberships at any time, and does not provide price protection or refunds in the event of promotions or price decreases.</p>
		<h3>3.3 – Refund/Cancellation Policy</h3>
		<p>If you are dissatisfied with the Product for any reason, PHOTOS in the MAIL will refund the amount paid for your most recent month of service. Refund requests must be made directly to PHOTOS in the MAIL at shutterbug@photosinthemail.com.  All refund requests must be made within thirty (30) days of the date of shipment by PHOTOS in the MAIL. PHOTOS in the MAIL is not liable for products that are damaged or lost in transit to PHOTOS in the MAIL.
		Promptly following PHOTOS in the MAIL’s receipt of your request (typically within five (5) business days), PHOTOS in the MAIL will credit the amount paid for the returned product (less any shipping and handling costs/fees related to the original purchase, which are non-refundable) to the credit card you used to make the original purchase. Notwithstanding the foregoing, PHOTOS in the MAIL does not control when a specific credit card company processes a chargeback transaction. You are responsible for contacting your credit card company if you have questions about the status of the chargeback.</p>
		<p>PHOTOS in the MAIL will not provide a refund for a request that is received by PHOTOS in the MAIL more than thirty (30) days after the date of original shipment. PHOTOS in the MAIL also does not provide a refund for returned products that are damaged due to misuse, lack of care, mishandling, accident, abuse or other abnormal use.</p>
		<h3>3.4 – Payment Methods; Automatic Membership Renewals and Membership Cancellation Policy</h3>
		<p>PHOTOS in the MAIL accepts credit card payments only. You agree to pay all fees charged to your account based on PHOTOS in the MAIL’s fees, charges, and billing terms in effect as shown on the payment page you first sign-up for a Membership to the Site. You are also responsible for paying any sales and use taxes and shipping and handling fees that may apply to your purchase of Products or Memberships based on the address that you provide as the shipping address when you register for a Membership, and you authorize PHOTOS in the MAIL or the third party payment processing service provider that we engage to charge your credit card for any such taxes and fees. All payments shall be made by credit card in advance prior to shipping the Products. If you do not pay on time or if your credit card cannot be charged for any reason, PHOTOS in the MAIL reserves the right to either suspend or terminate your account and Membership and terminate these Terms of Service. All sales and payments will be in US Dollars.</p>
		<p>PHOTOS in the MAIL and PHOTOS in the MAIL's third party payment service provider may receive updated credit card information from your credit card issuer. The disbursement of the updated credit card information is provided to PHOTOS in the MAIL and PHOTOS in the MAIL's third party payment service provider at the election of your credit card issuer. Neither PHOTOS in the MAIL nor PHOTOS in the MAIL's third party payment service provider are responsible for the distribution of your credit card information. It is at the sole election of your credit card issuer. Your credit card issuer may give you the right to opt out of the update service. It is Your responsibility to contact Your credit card issuer with regards to Your right to opt out of the update service.</p>
		<p>IMPORTANT NOTICE TO CONSUMER: PHOTOS in the MAIL will automatically renew your Membership on each monthly anniversary date of the Membership and, as authorized by You during the Membership sign-up process, will charge your credit card with the applicable Membership fee and any shipping and handling costs and sales or similar taxes that may be imposed on your Membership fee payments. Each Membership renewal period is for one month. You may cancel your Membership at any time by logging on to your account within photosinthemail.com. To cancel a membership, please login to your account on the Site and select the “cancellation” option on your account page.  All cancellation requests must be received by the first day of the month. Cancellation requests received after the first of the month shall take effect the following month. If you have any problems, please email shutterbug@photosinthemail.com. PHOTOS in the MAIL requires a reasonable amount of time to process your Membership cancellation request. If you cancel your Membership, you will enjoy your Membership benefits until the end of the then-current Membership term, and your Membership benefits will expire at the end of the then-current Membership term for which you have paid. You will not be eligible for a prorated refund of any portion of the Membership fees paid for any unused days of the then-current Membership term.</p>
		<h3>3.5 – Shipping and Product Acceptance</h3>
		<p>The shipment date will be determined according to your registration date.  Your first shipment will be delivered approximately 42 days after your registration date.  After you first shipment, you will receive monthly shipments 12 days after your monthly anniversary date.  Shipping dates are estimates only. All shipments are sent Priority Mail or First-Class mail via the US Postal Service. The risk of loss and title for all Products purchased via the Site pass to the Customer upon delivery of the item to the carrier.</p>
		<h3>3.6 – What if pictures are below the number of selected package are no pictures are submitted for a month?</h3>
		<p>PHOTOS in the MAIL will only print, pack, and ship that are sent to them via email between the “SMILE” dates which are designated upon registration.  For example, if a subscriber selects the $ 5 per month option for 15 pictures, and they only email 10 pictures, then only 10 pictures will be sent to the subscriber for that particular month.  There will not be any carryover to the following month.  If PHOTOS in the MAIL does not receive any pictures between the “SMILE” dates which are designated upon registration, then a package will not be sent to the subscriber for that particular month but charges will still be applied to the subscribers credit card.</p>
		<h2>4 – PROPRIETARY RIGHTS</h2>
		<p>You hereby acknowledge and agree that PHOTOS in the MAIL or its licensors own all legal right, title and interest in and to the Site and Content, including, without limitation, any and all intellectual property and other proprietary rights which subsist in the Site and Content, whether such rights are registered or unregistered, and wherever in the world those rights may exist.</p>
		<p>PHOTOS in the MAIL is a trademark of PHOTOS in the MAIL in the United States. Other trademarks, names and logos on this Site are the property of their respective owners. Unless otherwise specified in this Agreement, all information and screens appearing on this Site, including Content, site design, text, graphics, logos, images and icons, as well as the arrangement thereof, are the sole property of PHOTOS in the MAIL, Copyright © 2014 PHOTOS in the MAIL.  All rights not expressly granted herein are reserved. Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner or license.</p>
		<h2>5 – DISCLAIMER OF WARRANTIES</h2>
		<p>THE SITE, CONTENT, PRODUCTS AND MEMBERSHIPS ARE FURNISHED TO YOU “AS IS” AND WITHOUT WARRANTIES, REPRESENTATIONS OR CONDITIONS, STATUTORY OR OTHERWISE, OF ANY KIND. PHOTOS IN THE MAIL, ON BEHALF OF ITSELF AND ITS AFFILIATES, LICENSORS, SUPPLIERS AND THIRD PARTY SERVICE PROVIDERS, AND EACH OF THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS, SUCCESSORS, AND ASSIGNS (COLLECTIVELY, THE “PHOTOS IN THE MAIL PARTIES”): (A) EXPRESSLY DISCLAIMS ALL REPRESENTATIONS, WARRANTIES AND CONDITIONS, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, TITLE, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE; (B) DOES NOT REPRESENT OR WARRANT THAT THE SITE, CONTENT, PRODUCTS OR MEMBERSHIPS WILL MEET YOUR REQUIREMENTS, OR THAT THE OPERATION OF THE SITE OR CONTENT WILL BE TIMELY, UNINTERRUPTED, STABLE, OR SECURE; (C) DOES NOT REPRESENT OR WARRANT THAT THE SITE, CONTENT, PRODUCTS OR MEMBERSHIPS WILL BE ERROR-FREE OR THAT ANY DEFECTS WILL BE CORRECTED; AND (D) DOES NOT MAKE ANY REPRESENTATIONS, WARRANTIES, OR CONDITIONS REGARDING THE USE OF THE USE OF THE SITE, CONTENT OR PRODUCTS IN TERMS OF THEIR ACCURACY, RELIABILITY, TIMELINESS, COMPLETENESS, OR OTHERWISE. YOUR USE OF THE SITE, CONTENT, PRODUCTS OR MEMBERSHIPS IS ENTIRELY AT YOUR OWN DISCRETION AND RISK AND YOU ASSUME TOTAL RESPONSIBILITY FOR YOUR USE OF THE SITE, CONTENT, PRODUCTS AND MEMBERSHIPS.</p>
		<p>THIS LIMITATION OF REMEDIES IS A PART OF THE BARGAIN BETWEEN YOU AND PHOTOS IN THE MAIL. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY PHOTOS IN THE MAIL OR ANY PERSON ON BEHALF OF PHOTOS IN THE MAIL SHALL CREATE A WARRANTY OR CONDITION, OR IN ANY WAY CHANGE THIS EXCLUSION OF WARRANTY.</p>
		<p>NOTHING IN THIS SECTION 5 SHALL EXCLUDE OR LIMIT THE PHOTOS IN THE MAIL PARTIES’ WARRANTIES, REPRESENTATIONS OR CONDITIONS TO THE EXTENT THEY MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW, IN WHICH CASE, SUCH WARRANTIES, REPRESENTATIONS OR CONDITIONS WILL BE EXCLUDED AND LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
		<h2>6 – LIMITATION OF LIABILITY</h2>
		<p>IN NO EVENT SHALL ANY PHOTOS IN THE MAIL PARTY BE LIABLE TO YOU, OR ANY THIRD PARTY, FOR ANY SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, EXEMPLARY, RELIANCE, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, PROPERTY DAMAGE, LOSS OF VALUE OF THE PRODUCTS OR LOSS OF USE OF THE PRODUCTS, WHETHER BASED ON BREACH OF ANY EXPRESS OR IMPLIED WARRANTY OR CONDITION, BREACH OF CONTRACT OR TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE OR STRICT LIABILITY), EVEN IF A PHOTOS IN THE MAIL PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
		<h3>6.1</h3>
		<p>IF, NOTWITHSTANDING THE FOREGOING, A PHOTOS IN THE MAIL PARTY IS FOUND TO BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DAMAGE OR LOSS WHICH ARISES UNDER OR IN CONNECTION WITH YOUR USE OF THE SITE, CONTENT, PRODUCTS OR MEMBERSHIPS, THE RELEVANT PHOTOS IN THE MAIL PARTY’S TOTAL CUMULATIVE LIABILITY SHALL IN NO EVENT EXCEED THE GREATER OF: (A) THE AMOUNT YOU PAID PHOTOS IN THE MAIL FOR THE PRODUCTS OR MEMBERSHIP, AS APPLICABLE; AND (B) THE SUM OF ONE HUNDRED US DOLLARS (US$100).</p>
		<h3>6.2</h3>
		<p>NOTHING IN THIS SECTION 6 SHALL EXCLUDE OR LIMIT ANY PHOTOS IN THE MAIL PARTY’S LIABILITY FOR LOSSES WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW, IN WHICH CASE, SUCH PHOTOS IN THE MAIL PARTY’S LIABILITY WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
		<h2>7 – DISPUTE AND ARBITRATION; CLASS ACTION WAIVER; CHOICE OF LAW</h2>
		<h3>7.1 – Dispute and Arbitration; Class Action Waiver</h3>
		<p>Please read this carefully. It affects your rights.</p>
		<p>Summary:</p>
		<p>Most customer concerns can be resolved quickly and to a customer’s satisfaction by writing to our customer service department at shutterbug@photosinthemail.com or PHOTOS in the MAIL, Attn: Customer Service, 39 West Bridge Street, Dublin, OH  43017.  In the unlikely event that our customer service department is unable to resolve a complaint you may have to your satisfaction (or if we have not been able to resolve a dispute we have with you after attempting to do so informally), we each agree to resolve those disputes ARISING OUT OF THIS AGREEMENT (OTHER THAN THOSE RELATED TO PHOTOS IN THE MAIL’S ENFORCEMENT AND PROTECTION OF ITS NAME AND INTELLECTUAL PROPERTY RIGHTS) through binding arbitration or small claims court instead of in courts of general jurisdiction. This includes any claims against other parties relating to services or products provided or billed to you (such as our licensors, suppliers, dealers or third party vendors) whenever you also assert claims against us in the same proceeding.</p>
		<p>Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, allows for more limited discovery than in court, and is subject to very limited review by courts. The arbitrator must follow this Agreement and can award the same damages and relief that a court can award.
		We each also agree that this Agreement affects interstate commerce so that the Federal Arbitration Act and federal arbitration law apply (despite the choice of law provision in Section below). ANY ARBITRATION UNDER THIS AGREEMENT WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED. Neither you nor PHOTOS in the MAIL has the right to act as a class representative or class representative or participate as a member of a class of claimants with respect to any claim.</p>
		<p>All disputes relating in any way, directly or indirectly, to PHOTOS in the MAIL for breach of contract, breach of fiduciary duty, negligence, personal injury, intentional torts or other tort will be arbitrated according to an arbitrator selected by PHOTOS in the MAIL, including any dispute about the scope of this arbitration agreement, and including all questions about the types of disputes that are subject to this arbitration agreement, all of which you agree will be decided by the arbitrators, whose decision will be final and binding on you. Any issue concerning the extent to which a dispute is subject to arbitration, or concerning the applicability, interpretation or enforceability of this Agreement, including any contention that all or part of this agreement is invalid or unenforceable, shall be governed by the Federal Arbitration Act and resolved by the arbitrators. You acknowledge and agree that, in any arbitration proceeding, no depositions will be taken, and all other forms of discovery of facts will be limited to those things that the arbitrators determine, in their sole discretion, to be necessary. Further, in any arbitration proceeding, (i) there shall be no award of punitive, exemplary, incidental or consequential or other special damages, (ii) all damages claims and awards will be governed by the provisions of the Ohio Civil Code, and (iii) the parties will conduct the arbitration confidentially and expeditiously and will pay their own costs and expenses of arbitration, including their own attorneys’ fees. If you are unable to afford the arbitration fee, you agree to notify all persons against whom you have an arbitrable claim and give such persons the opportunity individually and as a group to pay such fee. The proceeding and the decision shall be kept confidential by the parties.</p>
		<h3>7.2 – Choice of Law</h3>
		<p>This Agreement is governed by the Federal Arbitration Act, applicable federal law, and the laws of the state of Ohio, without regard to its conflicts of laws rules. Foreign laws do not apply. Arbitration or court proceedings must be in Ohio. If any provision of the Agreement is invalid under the law of a particular jurisdiction, that provision will not apply in that jurisdiction. The United Nations Convention on Contracts for the International Sale of Goods is expressly excluded from this Agreement.</p>
		<h2>8 – ELECTRONIC COMMUNICATIONS; GENERAL TERMS</h2>
		<h3>8.1 – Electronic Communications</h3>
		<p>Whenever you visit our Site or send emails to us, you are communicating with us electronically. For that reason, you also consent to receive communications from us electronically. We will communicate with you by email (if you have provided your email address to us), by posting notices on our Site or by such other means as we may determine from time-to-time. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing, to the extent permitted by applicable law.</p>
		<h2>8.2 – General Terms</h2>
		<p>PHOTOS in the MAIL may issue a warning, temporarily suspend, indefinitely suspend or terminate any Customer’s right to use or access all or any part of the Site including any account thereon, without notice, for any reason in PHOTOS in the MAIL’s sole discretion, including without limitation breach of this agreement and/or violation of the Terms of Service, PHOTOS in the MAIL’s belief that such access would violate any applicable law, rule or regulation or would be harmful to the interests of, or potentially cause financial loss or legal liability to PHOTOS in the MAIL or another user of the Site. This Agreement and the Privacy Policy constitute the entire agreement between you and PHOTOS in the MAIL regarding its subject matter. PHOTOS in the MAIL will not be responsible for failures to fulfill any of its obligations due to causes beyond its control. The failure of PHOTOS in the MAIL to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision. If any part of this Agreement is held invalid, illegal or unenforceable, that provision shall be enforced to the maximum extent permissible so as to maintain the intent of this Agreement, and the other parts will remain in full force and effect. The parties shall at all times and for all purposes be deemed to be independent contractors and neither party nor its agents may bind the other party. This Agreement is only valid in the English language. This Agreement shall not be interpreted or construed to confer any rights or remedies on any third parties, except that each indemnified PHOTOS in the MAIL Party shall be a third party beneficiary hereunder. PHOTOS in the MAIL may assign or transfer its rights, or delegate any performance, under this Agreement to a third party in its sole discretion. Customer may not assign or otherwise transfer its rights, or delegate its performance, under this Agreement to any third party without in each and every case, PHOTOS in the MAIL’s express prior written consent. All terms which by their nature are intended to survive any termination of this Agreement, or any termination of your use of the Site, Content, Products or Memberships shall survive such termination.</p>
		<p>US</p>
		<p>Australia</p>
	

		<h1 id="privacy">Privacy Policy</h1>
		<p>PHOTOS in the MAIL values your privacy and is committed to protecting your personal information. PHOTOS in the MAIL is an online service that delivers prints of photos to its members once a month (“Services”). 
		This Privacy Policy (“Policy”) describes how and when PHOTOS IN THE MAIL collects, uses and shares your information when you use our Services. By using Our Sites and/or purchasing a Membership you consent to the collection, transfer, manipulation, storage, disclosure and other uses of your information as described in this Privacy Policy. Irrespective of which country you reside in or supply information from, you authorize PHOTOS IN THE MAIL to use your information in the United States and any other country where PHOTOS IN THE MAIL operates. This Policy is incorporated by reference into the PHOTOS in the MAIL Terms of Service. If you have any questions or comments about this Privacy Policy, please contact us at <a href="shutterbug@photosinthemail.com">shutterbug@photosinthemail.com</a>.</p>
		<h2>INFORMATION COLLECTION AND USE</h2>
		<p>The information We collect from you enables us to fulfill your request for our products (printed pictures that are derived from attachments sent to us via email), to send you information or content in which you may be interested, and keep you abreast of any updates related to our Site and your Membership. We also use this information to personalize and continually improve our Site, your experience, and to ultimately serve you better.</p>
		<p>Information Collected Upon Registration: You may browse our Site without registering. If you would like to place an order, become a member, and/or request information from us then we require you to register with us and become a member on our Sites. When you create, register, or edit your PHOTOS IN THE MAIL account, you provide some personal information, such as your name, email address, and password. Please safeguard your password and other personal information. You may be liable for unauthorized use of our web site, as well as have your private information used by others. In some circumstances, such as making a purchase of our products, we will request that you provide your credit card, debit card, or acceptable payment option and your billing address and shipping address. You are welcome to not provide this information, but if you do not wish to provide this information then there is no way for us to provide you with our products and Services and therefore you cannot become a member.</p>
		<p>Information We Collect Automatically: In addition, when you visit the Sites and/or register for Membership, we may collect certain information by automated means, such as cookies, web beacons, and other automated devices. A “cookie” is a text file that websites send to a visitor‘s computer or other Internet-connected device to uniquely identify the visitor’s browser or to store information or settings in the browser. A “web beacon,” also known as an Internet tag, pixel tag or clear GIF, is used to transmit information back to a web server. We also may use third-party website analytics tools (such as Omniture, Google Analytics, and Facebook Insights), that collect information about visitor traffic on the Sites. The information we may collect by automated means includes:</p>
		<ul>
		<li>Information about the devices our visitors use to access the Internet (such as the IP address and the device, browser, domain name and operating system type)</li>
		<li>URLs that refer visitors to our sites</li>
		<li>Dates and times of visits to our sites</li>
		<li>Information on actions taken on our sites (such as page views and site navigation patterns)</li>
		<li>A general geographic location (such as country and city) from which a visitor accesses our websites</li>
		<li>Search terms that visitors use to reach our sites and the webpage that led you to the Sites</li>
		</ul>
		<h2>COOKIES AND OTHER TRACKING TECHNOLOGY:</h2>
		<p>Cookies Information: Cookies are small pieces of information which are issued to your computer when you visit a website and which store and sometimes track information about your use of the Service. PHOTOS IN THE MAIL uses cookies to help recognize you as a repeat visitor, to improve the quality of our Service, and to try and make your browsing experience meaningful. When you enter our Sites, our web server sends a cookie to your computer which allows us to recognize your computer but not specifically who is using it. By associating the identification numbers in the cookies with other customer information when, for example, you log-in to the Service, then we know that the cookie information relates to you. Some of the cookies used by our Service are served by us, and some are served by third parties who are delivering services on our behalf. Most web browsers automatically accept cookies but, if you prefer, you can change your browser to prevent that or to notify you each time a cookie is set. You can also learn more about cookies by visiting www.allaboutcookies.org which includes additional useful information on cookies and how to block cookies using different browsers. By blocking or deleting cookies used on our Service, you may not be able to take full advantage of our Service.</p>
		<p>Local Storage Objects: We may use Flash Local Storage Objects (“Flash LSOs”) in order to store your Site preferences and to personalize your visit. Flash LSOs are different from browser cookies because of the amount and type of data stored. In addition, you cannot control, delete, or disable the acceptance of Flash LSOs through your browser. For more information on Flash LSOs, or to learn how to manage your settings for Flash cookies, go to the Adobe Flash Player Help Page, choose “Global Storage Settings Panel” and follow the instructions. To see the Flash LSOs currently on your computer, choose “ Website Storage Settings Panel” and follow the instructions to review and, if you choose, to delete any specific Flash LSO.</p>
		<p>Log File Information or Log Data: Our servers automatically record information ("Log Data") created by your use of the Services. Log Data may include information such as your IP address, browser type, operating system, the referring web page, pages visited, location, your mobile carrier, device and application IDs, search terms, and cookie information. We receive Log Data when you interact with our Services, for example, when you visit our websites, sign into our Services, interact with our email notifications, or visit a third-party website that includes a PHOTOS IN THE MAIL button or widget. PHOTOS IN THE MAIL uses Log Data to provide our Services and to measure, customize, and improve them. If not already done earlier, for example, as provided below for Widget Data, we will either delete Log Data or remove any common account identifiers, such as your username, full IP address, or email address, after 18 months.
		Clear Gifs Information : When you use the Service, we may employ clear gifs (a.k.a. Web Beacons), which are used to track the online usage patterns of our users anonymously. No personally identifiable information from your PHOTOS IN THE MAIL account is collected using these clear gifs. In addition, we may also use clear gifs in HTML-based emails sent to our users to track which emails are opened by recipients. The information is used to enable more accurate reporting, improve the effectiveness of our marketing, and make PHOTOS IN THE MAIL better for our users.</p>
		<p>Site Analytics: As noted, we may use automated devices and applications, such as Google Analytics, to evaluate usage of our Site. We also may use other analytic means to evaluate our Site. We use these tools to help us improve our Site, performance and user experiences.</p>
		<p>Links: PHOTOS IN THE MAIL may keep track of how you interact with links across our Services, including our email notifications, third-party services, and client applications, by redirecting clicks or through other means. We do this to help improve our Services, to provide more relevant advertising, and to be able to share aggregate click statistics such as how many times a particular link was clicked on.</p>
		<p>Third-Party Ad Networks : We may use third parties such as network advertisers to serve advertisements on Our Sites. We may display advertisements on Our Sites, participate in third party ad networks and make available to Our Sites users specific offers from third-party companies. Some of the advertisements you see on the Sites are delivered by third parties who also collect information through cookies, web beacons, and other technologies about your online activities, either on Our Web Sites or across the Internet, in an effort to understand your interests and deliver you advertisements that are tailored to your interests. These third parties include advertisers, advertising agencies, and ad networks that may collect information when you view or interact with one of their advertisements. Third parties that currently collect information on our Sites for the purpose of serving you with advertising tailored to your interest include, but are not limited to Atlas, BlueKai, DoubleClick, EyeWonder, Google, Mediamind, Audience Science and Pointroll. These companies may offer you a way to choose not to have your information used for advertising purposes. You can find more information by clicking on the company names above and following the links to each company's web site.
		In addition, some of these companies are members of the Network Advertising Initiative ("NAI"), which offers a single location to opt out of receiving tailored ads from member companies. To opt out of information collection by NAI member companies, or to obtain information about the technologies they use or their own privacy policies, please visit the NAI consumer opt out page. Also, through the Digital Advertising Alliance ("DAA"), several media and marketing associations have developed an industry self-regulatory program to give consumers a better understanding of and greater control over ads that are customized based on their online behavior across different Web Sites. CBS Interactive is committed to complying with the Self-Regulatory Program for Online Behavioral Advertising. To learn more and make choices about interest-based ads from participating third parties, please visit theDAA consumer opt out page. In the UK, the Internet Advertising Bureau ("IAB UK") has developed Good Practice Principles for Online Behavioural Targeting. More information and an opt out page to manage online behavioral advertising preferences with IAB UK member companies are available atYourOnlineChoices.com. Please note that if you choose to opt out of having your information used to deliver advertisements tailored to your interests, you will continue to see advertisements on our Web Sites, but these advertisements may not be as relevant to you.</p>
		<p>PHOTOS in the MAIL does not have access to the information these third parties may collect about your interests to deliver relevant advertising to you, and the information practices of these third parties are not covered by this Privacy Policy. In addition, PHOTOS IN THE MAIL with third parties to help us track the ads that are delivered to you, in particular to control the number of times you receive the same ad, and to analyze the effectiveness of advertising on the Sites.</p>
		<h2>INFORMATION SHARING AND DISCLOSURE</h2>
		<p>We do not disclose your private personal information except in the limited circumstances described here.
		Your Consent: We may share or disclose your information at your direction, such as when you authorize a third-party web client or application as log-in credentials when you register for Membership.
		Service Providers: We engage service providers to perform functions and provide services to us in the United States and abroad. We may share your private personal information with such service providers subject to confidentiality obligations consistent with this Privacy Policy, and on the condition that the third parties use your private personal data only on our behalf and pursuant to our instructions.</p>
		<p>Law and Harm: Notwithstanding anything to the contrary in this Policy, we may preserve or disclose your information if we believe that it is reasonably necessary to comply with a law, regulation or legal request; to protect the safety of any person; to address fraud, security or technical issues; or to protect PHOTOS IN THE MAIL's rights or property. However, nothing in this Privacy Policy is intended to limit any legal defenses or objections that you may have to a third party’s, including a government’s, request to disclose your information.</p>
		<p>Business Transfers: In the event that PHOTOS IN THE MAIL is involved in a bankruptcy, merger, acquisition, reorganization or sale of assets, your information may be sold or transferred as part of that transaction. The promises in this Privacy Policy will apply to your information as transferred to the new entity.</p>
		<h2>HOW WE PROTECT YOUR INFORMATION</h2>
		<p>We are committed to protecting the information we receive from you. We follow reasonable technical and management practices to help protect the confidentiality, security and integrity of data stored on Our system. While no computer system is completely secure, we believe the measures we have implemented reduce the likelihood of security problems to a level appropriate to the type of data involved. We have implemented commercially reasonable precautions, including, where appropriate, password protection, encryption, SSL, firewalls, and internal restrictions on who may access data to protect our Site and the information We collect from loss, misuse, and unauthorized access, disclosure, alteration, and destruction. The Sites encrypt your credit card number, debit card number, or other payment option and other personal information using secure socket layer (SSL) technology to provide for the secure transmission of the information from your personal computer to Our servers. In addition, only those employees and third parties who need access to you information in order to perform their duties are allowed such access. You should take steps to protect against unauthorized access to your password, phone, and computer by, among other things, signing off after using a shared computer, choosing a password that nobody else knows or can easily guess, and keeping your password private. Also, you should never share your log-in information with others. We are not responsible for any lost, stolen, or compromised passwords or for any activity on your account via unauthorized password activity. To change your Facebook password, you must go to the Facebook site and follow its procedures for changing your password.</p>
		<h2>MODIFYING YOUR PERSONAL INFORMATION</h2>
		<p>You may modify any personal information that you have submitted by logging into your account and updating your profile information. Please note that copies of information that you have updated, modified or deleted may remain viewable in cached and archived pages of the Site for a period of time. If you would like to access or modify your Facebook profile information, or adjust the types of information we receive from Facebook, you must adjust your Facebook account settings directly through Facebook. We have no control over how Facebook shares your information with us or other third parties. The information you provide to Facebook is subject to the Facebook Privacy Policy. You may also cancel your PHOTOS IN THE MAIL account. Just log-in to your account and cancel. We will try to cancel your account as soon as possible, but it may take up to fourteen (14) business days for our systems to completely implement this so you may still get correspondences from us during that time.</p>
		<h2>OUR POLICY TOWARDS CHILDREN</h2>
		<p>Our Services are not directed to persons under 13. If you become aware that your child has provided us with personal information without your consent, please contact us at shutterbug@photosinthemail.com. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we take steps to remove such information and terminate the child's account. You can find additional resources for parents and teens www.connectsafely.org.</p>
		<h2>CHANGES TO THIS POLICY</h2>
		<p>We may revise this Privacy Policy from time to time. The most current version of the policy will govern our use of your information and will always be at photosinthemail.com/privacy. If we make a change to this policy that, in our sole discretion, is material, we will notify you via an email to the email address associated with your account. By continuing to access or use the Services after those changes become effective, you agree to be bound by the revised Privacy Policy.</p>
		<p>US</p>
		<p>Australia</p>
	</div>
@stop